name: Daily Update Number

on:
  # schedule:
  #   # Runs at 10:06 AM UTC every day
  #   - cron: '11 10 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: "Your name"
        required: false
        default: "World"
      time:
        description: "Execution time"
        required: false
        default: "10:12"

jobs:
  update-number:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies if needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Execute the update_number.py script
      - name: Run update_number.py
        run: python update_number.py

      # Push changes back to the repository
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Coolboy_saurav"
          git config --global user.email "sauravm@arizona.edu"
          git add number.txt
          git commit -m "Updated number from GitHub Actions"
          git push
